#!/usr/bin/env python3.7
import logging
import sys

import regnotifier


if __name__ == "__main__":
    try:
        regnotifier.run()
    except Exception:
        logging.exception('')
        sys.exit(1)

